<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.0.6</Version>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>KeyMuse.Wpf</RootNamespace>
    <ApplicationIcon>..\..\assets\KeyMuse.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Using Remove="System.Drawing" />
    <ProjectReference Include="..\KeyMuse.Core\KeyMuse.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\..\assets\KeyMuse.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
